import { motion } from 'framer-motion'
import Button from '@/components/atoms/Button'
import { toast } from 'react-toastify'

const ShareButtons = ({ text, imageUrl }) => {
  const shareToWhatsApp = () => {
    const message = encodeURIComponent(`Check out this hilarious roast from BaklolGPT 2.0! 😂\n\n"${text}"\n\nGenerate your own at bakolgpt.com`)
    window.open(`https://wa.me/?text=${message}`, '_blank')
    toast.success('Opening WhatsApp...')
  }
  
  const shareToFacebook = () => {
    const url = encodeURIComponent(window.location.href)
    const quote = encodeURIComponent(`"${text}" - BaklolGPT 2.0`)
    window.open(`https://www.facebook.com/sharer/sharer.php?u=${url}&quote=${quote}`, '_blank')
    toast.success('Opening Facebook...')
  }
  
  const shareToInstagram = () => {
    // Instagram doesn't support direct sharing via URL, so we copy the text
    navigator.clipboard.writeText(`"${text}" - Generated by BaklolGPT 2.0\n\nGet roasted at bakolgpt.com`)
    toast.success('Text copied! Paste it on Instagram 📱')
  }
  
  const copyToClipboard = () => {
    navigator.clipboard.writeText(text)
    toast.success('Copied to clipboard! 📋')
  }
  
  const shareButtons = [
    {
      name: 'WhatsApp',
      icon: 'MessageCircle',
      color: 'bg-green-500 hover:bg-green-600',
      onClick: shareToWhatsApp
    },
    {
      name: 'Facebook',
      icon: 'Facebook',
      color: 'bg-blue-600 hover:bg-blue-700',
      onClick: shareToFacebook
    },
    {
      name: 'Instagram',
      icon: 'Instagram',
      color: 'bg-pink-500 hover:bg-pink-600',
      onClick: shareToInstagram
    },
    {
      name: 'Copy',
      icon: 'Copy',
      color: 'bg-gray-600 hover:bg-gray-700',
      onClick: copyToClipboard
    }
  ]
  
  return (
    <motion.div 
      className="flex flex-wrap gap-3 justify-center"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.5 }}
    >
      {shareButtons.map((button, index) => (
        <motion.button
          key={button.name}
          onClick={button.onClick}
          className={`
            flex items-center gap-2 px-4 py-2 rounded-xl text-white font-body font-medium
            ${button.color} transition-colors duration-200 btn-hover-scale
          `}
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.6 + index * 0.1 }}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <span className="text-lg">
            {button.name === 'WhatsApp' && '📱'}
            {button.name === 'Facebook' && '📘'}
            {button.name === 'Instagram' && '📸'}
            {button.name === 'Copy' && '📋'}
          </span>
          <span className="hidden sm:inline">{button.name}</span>
        </motion.button>
      ))}
    </motion.div>
  )
}

export default ShareButtons